# Generated by Django 2.2 on 2019-04-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190406_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='time_created',
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.CharField(default='Public', help_text='Who created this note? :(', max_length=100),
        ),
    ]
