# Generated by Django 2.2 on 2019-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190406_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(default='Example Note', help_text='Name of the note', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(default='Note', help_text='The actual note'),
        ),
    ]
